### ISSUE TITLE
Display cut off by 166px rounded corner radius

### ISSUE THREAD

**Issue by MrNerdy42** [crdroidandroid/android_device_oneplus_instantnoodle#1]
The addition of the rounded corner radius in the overlay config causes to display to be "cut off", that is the latest build doesn't use the whole screen.

**Comment by firebird11** [comment]
check this build: 
https://sourceforge.net/projects/crdroid/files/instantnoodle/test/

**Comment by MrNerdy42** [comment]
Just flashed the build and the overlay looks good to me!

**Comment by firebird11** [comment]
nice
