### ISSUE TITLE
Light sensor shows too big value

### ISSUE THREAD

**Issue by ioctl-user** [crdroidandroid/android_device_oneplus_instantnoodle#4]
Here is the same problem as in LineageOS: light sensor shows value a few times more that it should be.

Error multiplier increases with the environment lighting.
This can be check with [this app](https://f-droid.org/en/packages/com.vonglasow.michael.satstat/).

**Comment by gwolf2u** [comment]
please provide issues in forum

**Comment by ioctl-user** [comment]
Could you give direct link to that forum?

I was written to xda-developers with some questions, it's look like that thread was in deep sleep state.
