### ISSUE TITLE
GCam horizon level updated with huge lag

### ISSUE THREAD

**Issue by ioctl-user** [crdroidandroid/android_device_oneplus_instantnoodle#5]
Try opening GCam and look at horizon level to reproduce.

Gravity sensor itself reacts fast as expected according to [this app](https://f-droid.org/en/packages/com.vonglasow.michael.satstat/).

**Comment by gwolf2u** [comment]
Gcam is not actually a ROM feature
also maybe provide logs in forum to better keep track of issue as GitHub is not quite the place for it
