### ISSUE TITLE
Battery life extension.

### ISSUE THREAD

**Issue by ioctl-user** [crdroidandroid/android_device_oneplus_instantnoodle#6]
Is it possible add some battery life extension features:

Limit maximum charge level, use charger power instead of battery when battery charged..
May be: limit charge current, voltage, battery temperature.

These features implemented in the acc Magisk module, but it requires root (so, some other apps will not work; OTA can kill firmware and user data). Also acc itself consumes a small but noticeable amount of energy.

**Comment by gwolf2u** [comment]
possible, maybe
we don't actually have a list of features to implement
