### ISSUE TITLE
Quick tap option causes black screen

### ISSUE THREAD

**Issue by AlDollaz** [crdroidandroid/android_device_oneplus_instantnoodle#7]
On the latest May 5th build, turning this option on results in a black screen that's impossible to get out of. The only solution was to clear data and start over. 

https://i.imgur.com/WU45sQi.png

Confirmed by other Telegram users. 
https://i.imgur.com/hDgD9AU.png
https://i.imgur.com/0SuIneL.png

**Comment by neobuddy89** [comment]
Fixed in latest source 2 days back.
